schema_version = "1.0.0"

id = "blendmax_importer"
version = "0.1.7"
name = "BlendMax Importer"
tagline = "Import BlendMax assets exported from 3ds Max"
maintainer = "MaxxingAll"
type = "add-on"

website = "https://github.com/MaxxingAll/BlendMax"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Import user-selected BlendMax packages and their packaged textures"
